version: "3.9"  # optional since v1.27.0
services:

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_USER: junnikym
      MYSQL_PASSWORD: mysql_password
      MYSQL_DATABASE: chat_db
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
        - "3306:3306"
    volumes:
        - database:/var/lib/mysql

  chat-service:
    build:
        context: .
        dockerfile: Dockerfile
    image: chat-service:latest
    ports:
        - "8080:8080"
    restart: on-failure
    links:
        - database
    depends_on:
        - database

# Volumes
volumes:
  database: